---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: boinc-amd64
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: boinc-amd64
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      boinc:
#        pod:
#          affinity:
#            nodeAffinity:
#              requiredDuringSchedulingIgnoredDuringExecution:
#                nodeSelectorTerms:
#                - matchExpressions:
#                  - key: node-role.kubernetes.io/worker
#                    operator: In
#                    values:
#                    - worker
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: boinc/client
              tag: intel
            env:
              TZ: "${TIMEZONE}"
#              BOINC_GUI_RPC_PASSWORD: "123"
              BOINC_CMD_LINE_OPTIONS: "--allow_remote_gui_rpc"
            envFrom:
              - secretRef:
                  name: boinc-amd64-secret
              - secretRef:
                  name: cluster-secrets
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 10m
              limits:
                cpu: 4000m
                memory: 4Gi

    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: boinc-amd64-gpu
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
        supplementalGroups:
          - 44 # video
          - 568
#      nodeSelector:
#        intel.feature.node.kubernetes.io/gpu: "true"
#        kubernetes.io/hostname: k3sworker1
#      annotations:
#        k8s.v1.cni.cncf.io/networks: |
#          [{
#            "name":"multus-iot",
#            "namespace": "kube-system",
#            "ips": ["172.16.20.99/24"]
#          }]
    service:
      app:
        controller: boinc
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_BOINC_ADDR_AMD64}
        ports:
          http:
            port: &port 80
          https:
            port: 443
          manager:
            port: 31416

    route:
      app:
        hostnames: ["boinc-amd64.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

#    ingress:
#      app:
#        annotations:
#          external-dns.alpha.kubernetes.io/target: internal.davidstewen.com
#        className: internal
#        hosts:
#          - host: boinc.davidstewen.com
#            paths:
#              - path: /
#                service:
#                  identifier: app
#                  port: http

    persistence:
      config:
        existingClaim: boinc-amd64-config
        globalMounts:
          - path: /var/lib/boinc
            readOnly: false

      dri:
        type: hostPath
        hostPath: /dev/dri
