---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns
  interval: 1h
  values:
    fullnameOverride: *app
    provider: pihole
    env:
      - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-pihole
            key: *name
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    extraArgs:
      - --pihole-server=http://192.168.10.195
      - --gateway-name=internal
    policy: sync
    sources: ["gateway-httproute"]
    triggerLoopOnEvent: true
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
