---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-vector
spec:
  schedule: "0 0 2 * * *"   # Daily, 2:00 UTC
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres-vector
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
