---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: alloy
  values:
    fullnameOverride: alloy
    alloy:
      configMap:
        create: false
        name: &name alloy-configmap
        key: config.alloy
      # -- Disables sending Grafana Labs anonymous usage stats
      # Alloy.
      enableReporting: false
      extraPorts:
        - name: tcp-syslog
          port: 514
          targetPort: 514
          protocol: TCP
        - name: tcp-syslog-ids
          port: 1514
          targetPort: 1514
          protocol: TCP
    controller:
      podAnnotations:
        configmap.reloader.stakater.com/reload: *name
    serviceAccount:
      create: true
    serviceMonitor:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        lbipam.cilium.io/ips: 10.200.15.229
