---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage
  namespace: &namespace storage
spec:
  path: ./kubernetes/apps/storage/garage/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app garage-webui
  namespace: &namespace storage
spec:
  path: ./kubernetes/apps/storage/garage/webui
  prune: false
  dependsOn:
    - name: garage
      namespace: storage
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
