---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app esphome
  namespace: &namespace home
spec:
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: multus-networks
      namespace: network
    - name: rook-ceph-cluster
      namespace: rook-ceph
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
#  components:
#    - ../../../../components/volsync
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
  path: ./kubernetes/apps/home/esphome/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substitute:
      APP: *app
#      VOLSYNC_CLAIM: esphome
#      VOLSYNC_CAPACITY: 5Gi
#      VOLSYNC_ACCESSMODES: ReadWriteMany
#      VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
#      VOLSYNC_STORAGECLASS: ceph-filesystem
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
