---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-uhd
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-uhd-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        SONARR__AUTH__APIKEY: "{{ .SONARR_UHD_API_KEY }}"
        SONARR__POSTGRES__HOST: &dbHost postgres18-rw.database.svc.cluster.local
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__USER: &dbUser "{{ .SONARR__POSTGRES_USER }}"
        SONARR__POSTGRES__PASSWORD: &dbPass "{{ .SONARR__POSTGRES_PASSWORD }}"
        SONARR__POSTGRES__MAINDB: sonarr_uhd_main
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: sonarr_uhd_main sonarr_uhd_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: sonarr-uhd
    - extract:
        key: cloudnative-pg
    - extract:
        key: homepage
    - extract:
        key: pushover
