apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:YTMOfhkSR5+Lm/0driXc95qMWN74s2SlZbT6Ocsb2YW9MDMuYzcB9A==,iv:so1XQxFk3txW05HKI3fqZ7Itlc7OsQV5ARAF6LUVCA4=,tag:xlMp7TP+es/YXirKEi7fIQ==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTS0NQb3h5bDZEWEhxRU9h
        RjZnRFlIem1NZStDTmY1OEllM05UUXZpZ2pnCkgvR0s3cEdGNTZyOVRlRXh4RGFD
        RXR6RVpURUxIaFN5UTg5U1NlT1BUMTAKLS0tIG1zZDkvVW5mMjloVGwySmpEOGU1
        RHQ4R3M4Zy81S25PRTg4OWxQVi9vUFEKedqwUS2cyKvnTPKyX/aQNJMMgQ9UfjMV
        aIpcN5hpbscDoACjHXl0bhUQghyaj/KHb8c8TZA1j+0NbSlYnHm6DA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:24:06Z"
  mac: ENC[AES256_GCM,data:mFyjxIYTd2DSPqgchBTwIsiK/fzrkvv2FxjeHS3R41wval50H8MepMWxPCeSzWYiVBIpUJa/c5ckLwf3K1Hgv56T9q7xyiLoF9b5pCC5c23CgKkZXZQ1PbsXc+Guie9+hcOPD6FvNB92Fetz0hzfBLzCKrBOV2KsCYQjz81A6Sc=,iv:rteLppCxb8DR0kIvlmeCuOK6ZRRe8m7AfkrKTbJxMSs=,tag:bZhXRiYExOYxVR3I/nt2fw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
