apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:M3ewBaTjehBEMwUKkjqtDeLLMo2nM+n6neuKkDcOGCHunLr63twPMw==,iv:m1bn/jNmvpchMdaa95zkAqd09x318ZrKfdc/7SHGWis=,tag:lgwmEwJEqjm5eKF6C7/JIg==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMkxNYmZwbHU4N2d5NjE5
        VnhIK3hZaXFNbm1NcVBJbnVxSlhxbDFjT1hNCjdobXd2Q1BtUGY3a2tIS01sY2cr
        dWZ3TTAwclQyV0JQcWlQQ0hIYnZhYmsKLS0tIE1nNHl4cmpCbDZndlE2RXl5REFQ
        ckZMYi9PWS8vNjNUMWZHakZkMzZMbnMKey6WEJnDwQWgkQPYdwSR9c65WYfhqTiP
        UWjUfre4B3Wr3xM4fDaSh1KexLycmx9YoTnEXAbUOVqSXx9b3b6M2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:53:48Z"
  mac: ENC[AES256_GCM,data:FIl7P8bh57u9zj3lL1nkT6Rely/WrV1hrVv4J5Q+u/LLq81XfXhqpnir3t8gqyKMhvofP/IqbcegCNM4OzoSW57aZJEVQFbunLhOGNyWZ+GnPFzVGcgvx/7EQMGe8e2Cvd0kgSBnONeRRcwTYMJZC3jhMMTIEVTrv++WOdBvqIg=,iv:oE5unabb8Vd1iFnIJCwaFpaeSXXz8yj1soKUqWoRpiw=,tag:CP7cagN9I87QJ0SkNg2ZgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
