apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:WjCFHDbZ926WdT1bj2LaB/ysCk65D2WCiqFlDrqKlaY+cmogkZpJIg==,iv:+2QApiQDA0OjUOhxlOBVltxMpDf+GBiEOQQCrRRsq6Y=,tag:HJ2R2rfvcZOuo7xysD3tJg==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZEVIaGdjMXl4b3YzdFUy
        ZDc0Ly93NU9sdndJUFlQQ3ZIcVVSbEJSNWtrCkprRTdzVEd1MDRkOFd3cUx6K2Ny
        bUNvTWlFUzRYYi9MeEdzeXZlR1hHcU0KLS0tIEhOMUVhbDBmS3h2TDZoc1hEeWNm
        VmY1OStSYUNlbkhFZTZnU29keWlkYWsK+lTKQTYddtnYtaQwXDJvDIrv1Ek28lHJ
        MJMcL6QuvVYhWyiTM8LvpWj/9O+GVpdt4RDoS/vO4YYdlncuAtMfHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:33:26Z"
  mac: ENC[AES256_GCM,data:d1bLAEkTrNfH/YU5PlBzlR9J0dKJEQ4qqisICHBqguWA4tvuA5dtkiJM/RDMgk0+4lBamLTEV5IffkgIkJ4BzbzTDN5/XpnyRaXpbDgPFLU5d7WN9EWo0CBjSfqqDD8WYWBauBBWcWrEdIEClA8rfbgoRieVPTMUvfDtXAZaGLE=,iv:MPtF6XM1+oXyQJx6iVr72cz+n2litoJlEwpKHMltkNw=,tag:pnwBhpFlMoQGpWjLwZe9Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
