apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:o/rPJTgJr0KXv0QDdeDfWHYNE5nTKuQVOjAdrDPvy3txKa/e3Lvnsw==,iv:XxvDje548N6YxNhVWDPTEov7t3iKrNhU3vbXEN00lHI=,tag:gRzMr5fRwQefcGdNJAOQJQ==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidDIvTEpXY2Q2VTBXOW5y
        NWhpU1VBaldrNUY0V3c1YTdiVzBLUWdtZm1vCnpWRFFEKzB1VFhmQlpQak5EVUp5
        MU9LRFJ4eS8zZ0tHeGdvQllnbXUyMHMKLS0tICt6WkphQkJwNHJmREFKYmZqMitM
        bENGQ1ZMaGs5ZlUwdlZNSGg1N3BWZlkK1N+N34uQUZhhiQHXwNNLL64y2gIlChb6
        Y8pMfgn3PzoGmRJn81WR0OqLqLsgJpveJq0qkQqkIKTWgqbyTL8riA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:31:04Z"
  mac: ENC[AES256_GCM,data:lna9qk5wLFo4FwRRkoDSfAoCWCtgSV/Le7tgHxcli1XRTCCT+8OGD450k3lMJMuVkLGV+mhK2VO02Vq6mFvB6wsX06ei1Ex3MzfvxbiepGXJsFE+oB1+g8rOSc2a5y7ox37RNN3GaakAlxDqibH5PllYEaBuewdAyU3QTNRsSiM=,iv:QxZwgt3dy3aOjwubEVZXSzDHbiphUL125d3etqfJP2U=,tag:P519h/2ol8+Z3pwr917A9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
