apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:y3zDh5vxVtIAOZ0qJphARAAtxSQYp96sosksLSMBtQqjtGoO6ZeauA==,iv:dR/ZP23IY6+sqhoWZMq4N0rjH3rcWypODsmhYKG2eZU=,tag:XUTsus4Qj8Gc8t0vMHT7NQ==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL0lWQzVBYlM0akUwT3E0
        Y3NUYnI1QldWWkJMOXlLSkgrQStnbVM2N0QwCngwaGxrRUFkOXdMNUM3WXpNODdS
        am1ISFNaTFo0eEFNeU53bjVPK1YzbGsKLS0tIHhzZE04L2poK1hzQVFpcGEwenhQ
        S1kwL2lCdHppMEpVUzlNR1NxK3FFVncKumhskpt/gPt25C/ThGTBXFUM0F9+jMXO
        RenXYfYd9hdVStn1t7F39dURlBkIhxRBaTnNB0LSC4HmTTqucIMblA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:00:43Z"
  mac: ENC[AES256_GCM,data:59hfQc84HhKNJuQkNR7XDRr+h6xgo8wlB4Rxd3VzqGTXr66c4MF/QL1V54BZB1ju5vXXVrnKxIRhum87F0XfDibPKhzWWPKewDqfNQEA+hsQISLBlAjI4pUPVtCEWCxqC/3NnUUuFcb5rT+utCtxX19oM7fvMKqrioSKMT8//88=,iv:55kSLQUxHDZs7Ktjx4TMgfzoEbLjCktktSrEWzz0Q0k=,tag:591v8Ig5enoND4NwuOeFUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
