apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:w1IB2z+ZNiTtf8qi/po8M3GORJZ215NjLFSvYOLQG6RNyU3wlKNZyA==,iv:hE28vE0w4ziIhyIUE5fD1mxy3i+56oS9xHhk6Glwo8o=,tag:esf8u5t2xDk6pe7DuNKsDg==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMXg4RDBlYXNqUXYzeFpX
        ODJDYzJYZEd5UU10SXljSVMrb1puZ3hvU0hRCkNrMkhKN1Z5alBtVng2OEJXY0du
        SUlYcytuSm9ZS0NxekxiejJ1dE9CSUkKLS0tIG9BOENocFM5aSsxVHNQRjdZSC9z
        SVhIUzRJOUxuVm1VSjJ0MDJWa3F0cmsKrrKF/n3UiCQ+eQGuvNXm5LNrqBDzAFBS
        CIarhmUa4GsYlE2yRGKzUJkbnUE2ADsorsJYh8gvSAmapMDAlKecXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T10:27:58Z"
  mac: ENC[AES256_GCM,data:dPEPTiF3WXlPZDcNfHuxp3uQ/GN6776PSJXPWSlLc4fwTUf7SPxFcJmGvqbzvFvct4Ie4H1ZBVR3veS8tDLKiN4wRbgOwtv0ofCkBkk/IjySKTog97oN/aBgcypGw9UPhaPUb139Ddn/wl/nPQPB4/iEPYs43goWIzhI2cROs2s=,iv:SuwMk/pSC0hsghsB3OOLhXdZgUIW6bPwgzP0kU64eZY=,tag:Nvo4fLEYv7kFv4GfpHnsSQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
