apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
stringData:
  admin-password: ENC[AES256_GCM,data:YQmdGs/z6BO+,iv:LW3ITCMj8+x9SsONPcqKH53EcdPiJlqoBhjmmNKHgnE=,tag:iEZabvKKP4okSV54Y5qTuQ==,type:str]
  admin-user: ENC[AES256_GCM,data:FyntO4c=,iv:DLKxQJNkHH6xCs6UqKRg29x7x4xv5ZTCIH2LljjQ+Wk=,tag:W6DH5xjhTVVGsOFzpXKFbQ==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VmQwY1NTemNsb0hzN2Uv
        WU1oNndKTTQzWUlSWG9YVTRyN1NBUk5rTURnClNvN2pPOHdiRU03TFh3TG5yRHBy
        RVBHVzBwaGU5amZCNUdhVEp1WFE3elkKLS0tIFBqaDZyVUxjaEE2S0dYNldBek1S
        eDczN3RyWW5lYTJ5M3Izc3E1ellpRGsKnGB+rHf6dcApjfp/EfvybvpA3ORN2lNU
        RQGoZY+0sI+tP/XthCKFzQm0lKTqlNk26SUQ7M/Jk3EF4qaFnxMFqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T12:54:11Z"
  mac: ENC[AES256_GCM,data:vCt/+hH6OqPjkD3LSlmOIgBRR3XEvN5EwhSzeMKfnwtuettSLsycRKd/BPaWpjtlRPsxMSu8QdVZRvvima4Rptv82i+eDC1cxZxzopnLAx/Z8WaL1SEjdMmw43ACQ3moa6xxEfINMK+FxD/JiZhHnPiAgdnVf3p+6MIqbILNkPc=,iv:buLFAvYlJTv/AudtOFx/9986a4WnleZ1iv/HSjnKqTA=,tag:IifJuUPMdwFiJIzFvfrfjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
