---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless-scan
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: paperless-scan
  values:
    controllers:
      paperless-scan:
        replicas: 1
#        labels:
#          nfsMount: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/philippmundhenk/brotherscannerdocker
              tag: latest@sha256:633be873cbd7915f167086ce6f463010d3dd05c8d6a72070bfa2dec1a3e4a533
            env:
              UID: 1000
              GID: 1000
              TZ: Australia/Victoria
              NAME: Scanner
              MODEL: MFC-L2880DW
              RESOLUTION: 300
              IPADDRESS: 192.168.10.81 # IP Address of your scanner
              HOST_IPADDRESS: &ip 10.200.15.243
              WEBSERVER: true
              DISABLE_GUI_SCANTOEMAIL: true
              DISABLE_GUI_SCANTOIMAGE: true
              DISABLE_GUI_SCANTOOCR: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        forceRename: *app
        primary: true
        ports:
          http:
            port: &httpPort 80
      brother:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: *ip
        ports:
          scan-udp:
            port: 54925
            protocol: UDP
          scan-tcp:
            port: 54921
            protocol: TCP
          snmp:
            port: 161
            protocol: UDP
#    ingress:
#      app:
#        className: traefik-internal
#        annotations:
#          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN_INTERNAL}"
#          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
#          traefik.ingress.kubernetes.io/router.middlewares: "networking-traefik-middleware-chain-tinyauth@kubernetescrd"
#        hosts:
#          - host: &host "scan.${SECRET_DOMAIN_INTERNAL}"
#            paths:
#              - path: /
#                service:
#                  identifier: app
#                  port: http
#        tls:
#          - hosts:
#              - *host
#            secretName: "${SECRET_DOMAIN/./-}-production-tls"

    route:
      app:
        hostnames: ["scan.davidstewen.com"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *httpPort

    persistence:
      nas:
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/media/paperless/consume
        globalMounts:
          - path: /scans
