apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZgxyAu/jUc+g4OEn8Qlu,iv:x9mrwE/gfPEwIMKwh3tUYBaxsBx7fzLTgwN1VSlPEjc=,tag:ncZq3M8BVuEuQmJ2jVbDHg==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd2l6T2llUjRLOFlYZEhv
        eGxzQjBnczFPUGRHOGNObVRRcTBJb3Z1SXpJCkVWRTBOVmhuMXF6ZHE0Y0hlWG9S
        dXF1QUMzcm9ZR3BrT3pndis5ZGdSOXMKLS0tIGtmU3ZXQWtJQkd4OFBMOGJQbGwy
        djdsUWZmeDBJc0xIL1pZMzJQWmYrRlUKSpZWWN6fPxNlEG0riYoTNynYiq60hacN
        uisB2N03gGr6zawFAfGuLTl5o0DslO9o33SadjWO0K5MgcyLt2irXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:00:43Z"
  mac: ENC[AES256_GCM,data:lpwx6iyn0NejshKByZzsDNDXh2n5e8bpQufZa3cs9hpMpjIlVo1wBLP8RYoGKqoJGDbSkbA2S7Szkfyqa2c8b5DrbIMLFX+tRaGVMKkIRUby28LTNJe5+ZjUiGEq5BoUZVfgrO+2FBfBf6d1oZ9irVtJ22pGt82VtQ++qWHFD2s=,iv:bbde9fjYdFEzCDYjUn7e+fDlpGWMPViMr4yjAA/Pf+k=,tag:YlbXtcC7lfmCyrSdxgZ7YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
