apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:IaPmX661o06V+L7zJSuG,iv:jS4zs4MKesK62XHEOP7JKTBElideBaxeA54ppPyoLrg=,tag:Kt0nhOBTcF4kn0A9XMMWZA==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRDBHbFR2UEhEZmJZQWY2
        RUk3d1pRMkdrN3VGczFVOTkzYnR0dlBIOEVjCnVqZmU5dWtIRXdHU1pTZkJ5Z05n
        V2thcld6aTBHWkxQazZNMHZhN0E1S28KLS0tIE5kQnZJaHhSTG5pamFOajJ3cjZY
        dWlHSHRneXFUem9KVTZvUnRUYzRvWUUKsGuUksCr4OrzBIOFT7bXZiE1Xz9NmdRa
        xO5RAibBtkC2le44sxlvnZpDm0jyf7dFLjmhiIxlTCXx8b3ewfLNCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:53:48Z"
  mac: ENC[AES256_GCM,data:bGRqs33fD8SHAuTdM7iqU34scqlblETwhirC7UZswGbQ9ph+SRWhjfWBeQfRsAenQIeAz64bFQRq6dclm6HQpropJ7YwhM1EP/qUhfKd1WAhzRjSyEdfPLLXLn/WXO7K6rrXyHQs6nc7Dx//7zrJVq6fi77ncviWsiS2kJzqli8=,iv:RanHN3Xdx0MQ+/Q0sncn5I1TR3C4KnjaP0HCBdBZP4E=,tag:eoK/se4YHd3x2TfHFhsG7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
