apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:oPHYyOyB0zgfYgB1G1qS,iv:KyP4dga3tXQgRAaFnmedSmUHQOuPOd2GDtbm/fgTMa0=,tag:k8Hte3EvMXhf/6RGa19GuA==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa01iTG9yTE1tcU9ITm5w
        cHJYbnFzV0g1U3hCbVF4bXFxMExiK1RyRVIwCk0zMFJaNFRma2xlc3NDTEkydjJq
        ajVIVHB5NlF2VmQrN0RmdVprOEljTFUKLS0tIHhkZEhPdC9vcjVRS1J5ekdMdFhI
        WUJDdm9OckpuN2FCd0JJNHNtSTcrOEEKsiQfcS6+VJ+AAz0nfW+m+xW8j2/hd4F/
        xFVVYc2TshanEFi4OHK5PAaLKODvCmpoiFA3v3hSBb0B5yW7jfmB2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T10:27:58Z"
  mac: ENC[AES256_GCM,data:5nulIgkl2uprHa+9pe6HXbbS8IOUinSdnK5C3WcMElhxeFkFyFkfX6TIUyp0qA41P0OY0hkfglxJM7GuubD6JZceUR4YvCZ/qj6PYaV4fICK7NDH3GDaoF0yjr9I7ofuABCrj9oquO2aUdvgElDwROsoITGVIT9vi6JhnRPi/c8=,iv:rPdNESfoeCLFCyztwHgPjwgPtxXa2KvwNKnAWLKk5ew=,tag:n2WPfjKQK0mtqgOzFWAXOA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
