apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:VASnKGShXPNJTWp1Tzui,iv:pvP7Ric245AShjnrH5ccFjP9WY10+QOPfdmbZ608Ky8=,tag:y98KNqu1/QV1kM8mi25ziQ==,type:str]
  SVC_MC_ADDR: ENC[AES256_GCM,data:sGMIFXdDMgaBxSY3rg==,iv:SiGMC41Uv4Plk3v7ICoq8QDHE9DCGWvSlwhWgbz/xdg=,tag:MJS4u+37nClZhdq3bIKJpw==,type:str]
  SVC_MQTT_ADDR: ENC[AES256_GCM,data:YRiGRFBQLSg0XwsJ7g==,iv:CcuZaRkmt6r4b8VDg2+WParn1Ffi4ZJxWeKMZpNN6uI=,tag:xle68ZrefEc71Wx1pdsvdg==,type:str]
  PI3B_IP: ENC[AES256_GCM,data:8WvXfbaptzPkxQQ2FA==,iv:c5E2+1Ea0B6kYvgydWqNcV9lJvc9oB7WmQIO+sTpTcA=,tag:1ozGj2uTK/B/UqNr/V/0Xg==,type:str]
  SVC_HASS_ADDR: ENC[AES256_GCM,data:gkjn8gUIz6fR9iWaOQ==,iv:Irmza6uQnnn88ib+oRztFx3odu7GTXH5YPMy+r51C70=,tag:tsS5u5Tv6J6UBilvTnGFkw==,type:str]
  SVC_PLEX_ADDR: ENC[AES256_GCM,data:J4ShGAoqs5uwUMvt2A==,iv:1CgD8zkJNmcTddF/QxG+qVQjfnf6sfQc9lgrWbonRhc=,tag:S6mE8jh/jmmW3WcAapbYfw==,type:str]
  SVC_POSTGRES16_ADDR: ENC[AES256_GCM,data:3x8dJZt9t0NO4W30RQ==,iv:dWmLg+nCUxLorR8xQekHaf6VaABILieZgtWN5Simhqc=,tag:/jaYOJqhEmHcz1SYM4/5AA==,type:str]
  SVC_POSTGRES17_ADDR: ENC[AES256_GCM,data:GEBkUrRFVoVq1nuDDg==,iv:Wu6WUS8P1mo7zi2CA3Ry7zRUGTO45JEDcebyfDxYyM0=,tag:z9ZKSOkquzOQCuByDW/bQw==,type:str]
  SVC_POSTGRES18_ADDR: ENC[AES256_GCM,data:4Mg6Yd1Dt8SdI1kUUg==,iv:avthT4P/lzSd1EZErWiK/jaJy15MqXvuZ0FHZxhJBi8=,tag:z54xWK/UaLm7VscTA+ZKDA==,type:str]
  SVC_QBITTORENT_ADDR: ENC[AES256_GCM,data:fDna6mz4UFcd/cxhmQ==,iv:j27iDmAFIMyfKTBdlIsDv9H8YTgodzDgwduvikGLaNE=,tag:rQ0rTG51HAc9GjZeEKNVsg==,type:str]
  SVC_LOCALAI_ADDR: ENC[AES256_GCM,data:Y9NprT0AyI9XojbW/w==,iv:X+cHkOgO+S5qV9TWRgNPR0buV5XcfGx6YItJJR53Grs=,tag:xh4o8wV+4nqR67Jt9ksRzg==,type:str]
  SVC_SMTP_ADDR: ENC[AES256_GCM,data:gaY764aSzroEa0wR0g==,iv:IUzRng2ftdiH1rHCPUt39NhhOLGxM4mBxYLZoxH9HGA=,tag:30Wt2hug6rxjUQnldgSK+g==,type:str]
  SVC_UNIFI_ADDR: ENC[AES256_GCM,data:aXC+rmLheilRhSE6NA==,iv:HTVN1Vk2kHyJYlmAnOAaneGnC5vvFCODVLgODUp+9E0=,tag:Y61zkYhF3/Zw7vLGidbbCw==,type:str]
  SVC_WYOMING_PIPER_ADDR: ENC[AES256_GCM,data:jYrchCItL2RdiQxsNg==,iv:KxDzOkw3Xf0nuLUYDGYdo/dX1tMwzxnMSawGaUbEMuw=,tag:0T5s34MtvDtlRturMNYUwA==,type:str]
  SVC_WYOMING_WHISPER_ADDR: ENC[AES256_GCM,data:lQH9AmMbo5DKUJu8SA==,iv:isJwXCyc4SjoVmkhCyismJGcxsjKFZp4D5qFlQYHB80=,tag:81mofEjQLQEyOMNMtjOjhQ==,type:str]
  SVC_WYOMING_WAKEWORD_ADDR: ENC[AES256_GCM,data:C98IHC5r/ujioVNcHQ==,iv:0vadAAmy5K/07cZNX5MDYV5mSBrOvLsEEtPfute+53Q=,tag:JuLnYbwPV+tVELkskylTYQ==,type:str]
  SVC_FRIGATE_ADDR: ENC[AES256_GCM,data:D7wN40GryrC4vf8APA==,iv:IjgSFE/6JZV6GbjkiHeLoTJnExMjbPYtHRBnMgdX2iM=,tag:BiufOdSAdxAVX1jhXu8Nkg==,type:str]
  SVC_BOINC_ADDR_AMD64: ENC[AES256_GCM,data:DiVybIECzDHN44pJ1w==,iv:dm1BD3URIt2AIhQT/8zDmMrQnvbqe4CYsYOu+9v+KRU=,tag:v87Z7IQBR2msVkmAtKYeHg==,type:str]
  SVC_BOINC_ADDR_ARM64: ENC[AES256_GCM,data:y8CiTOsFIIeimyGkew==,iv:J57LL/LDGVhZi3girFgpsVoCKl9LyjP22GiLQoCqJbQ=,tag:fDaFnfNnvR775EZ7sKu5xA==,type:str]
  SVC_OLLAMA_ADDR: ENC[AES256_GCM,data:i6tFRytP1C+L7gCp6Q==,iv:dTpaKGvo8RzHWn+ubi7+OtR3x9lj89lKUiwGEjFlDiA=,tag:vhh39fe8r6iVSrk4P73uRQ==,type:str]
  NAS_IP: ENC[AES256_GCM,data:quoCJBlZ1DZ58A5VqA==,iv:8dP7EAx6uJhLVtIIZ7MEawRWPRvya79HM8um0m0C6Lg=,tag:Pht2vkVHUzv6BazhDjMMGg==,type:str]
  HASS_PI4: ENC[AES256_GCM,data:ID+F4Oz3NtkJcLQMBw==,iv:bMxMKQo4PcGLrlyjbRCgsBoFbAItofXA9pP+EE+3T7k=,tag:m9pbiahlHPAgg4jCW+6PLA==,type:str]
  HASS_YELLOW: ENC[AES256_GCM,data:DIG6VkvZXRhiOaLcHw==,iv:z7ejiANq5vT2Ke9fouAQFEsnn838wTospwwwMPuY2gc=,tag:qev6lswy7mGoAEUF5weasw==,type:str]
  PIHOLE_IP: ENC[AES256_GCM,data:gwnF5am3GT+oC1HFkTE=,iv:nr0iYs8yehaKIaEzjDBrddTM2nCna55DpHa3+0b9Cvo=,tag:YSEel9U3G1JNLXVXT8Uoyg==,type:str]
  SVC_PIHOLEK_ADDR: ENC[AES256_GCM,data:wpGOjOrW7i+XHAwu6Q==,iv:/ULDgukfZtIk9jZCXl9ealo87cVCzAm88CZ5pB9OaSE=,tag:78pDGr/6ouTQydTBST9HMA==,type:str]
  SYN_MINIO: ENC[AES256_GCM,data:EHysZ6xZvmCxb1Rgxhk=,iv:vXrLeuWl+t+tPTQvnko5i9G3yEa156nEvbmFdwd0i6c=,tag:PpMxr8PPE4hF2HV3oZNF3w==,type:str]
  NFS_SERVER_CAMERAS_DIR: ENC[AES256_GCM,data:BSys7Pp9PBjKy7fIeuCr5d6PsxparSdA2romwPM4CTFASsA0EUMfd93aJQ==,iv:aXUBCmjfBbPBilUL7Lo6BcDcAevDOAWDeU7OGRPU3bY=,tag:huKX4NWQuNAb21LtLFFIgA==,type:str]
  SVC_TDARR_ADDR: ENC[AES256_GCM,data:EzJijG/TNTbx/c/9nQ==,iv:sou3VezWb1Jlela65rY/eGQmAONl5xla9hgp7LbsXiE=,tag:9+iuilTAm0p0pKXw3Anu2w==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:arv1LnGbdHVX1GUGwLg3zMC3nA==,iv:i/iUDnH2HAxNdOjRHqK8h6TtUwKI7kiGbhjDYYPu0qI=,tag:Kzb7RWGBlKRKztcfUiHYuQ==,type:str]
  SVC_SYSLOG_ADDR: ENC[AES256_GCM,data:rvN23sBNLDaPXMXdTg==,iv:xxjnPjNwqK3IGPxXi8o4WhYCYOsUTw9iRXXU9RbqprM=,tag:Rsl2KbCVNG6/UbCRjxBB6A==,type:str]
  SVC_SYSLOG_IDS_ADDR: ENC[AES256_GCM,data:k81CzVohbg42sZKbnA==,iv:5ggTIh9JB1fTiq3uEMAs6m7Z5ZkEOarPO+wI6EkJr68=,tag:shs46uWAsY9HwoO9saGesA==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK3JKd29BSitwME10NFpF
        OFpvbmhQdnkwTW9zeDVwTDcyVmZLanVBWUNFCjdFMG9LQzFvak5IalVkY2FzZ1Zr
        WU14a3RNbXF6bHlST2RHUUg5cFhpZTAKLS0tIGlXWGNwM3VYZEQxYi92WC9PMVFB
        OTdPZUswNlAvcTF2VzRGMXZ5TlBNQk0KG5BqhMI0WnYskXtbTjLBH7qbT3V0KvVO
        h4Vdo4DOgvrputj2Hl4GIlTGzWphBjBwreav+BWNuVorVSrXK1241Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T11:43:05Z"
  mac: ENC[AES256_GCM,data:0TgsURsr3Rhum1Uu6BULlXD8g1LTE2/PFaUTunwQTg+gYOb7n0LTprY5aSjVJpeV8nOw2quLOw3jS7IOefT9iCZ5XLQRDrznwXytPvfGT0HKC5TTCcAfbgzP2EHCvCH9t6QXgz76/IHWsEntqMKa6veReM8uSPVJ1w7X+AJ+2jU=,iv:wwL9zodKXiTjP//xNupbaT4G1p6R39iC3MiCTOb9lyg=,tag:iDLqtRQZZiGaJwPvdPNyjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
