apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:mPDYoBeUK5AHWq5PFWi+,iv:ZEmpIPrSNvzJCqakw0CAl/aUdnoAIIrPK7h+4M80l7M=,tag:V+EuFr/dpXGOvHEIn7Ca+A==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdlZaRy9EVWVRMzlTMmxi
        MG5SUHN4Y0srYmpHbVdJTllvbVdQY0ZVdEFFCjNWQit6V0FmTGRuY05WS1FyZWVh
        cXBIdi8xRlZkMEVLcnppbFFqQ1AwbDgKLS0tIFBmSFRyV0pnV0swUXVMS1hxbGhK
        YzlpMnB2VHVNeTUyTWxKSjNGUUZEV2MKpwCXLHitGmweuxn8MeJeqqIMlrZB0Wcp
        7ZGH/NtChVLsAIE9v5VgyVz8kR1npyGsq7XEIm8Est6z+gQdSHD8IQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:31:04Z"
  mac: ENC[AES256_GCM,data:PmgGFP3O1w4KghVWkbWqIvhYY9G9rPTGjKYR7uxCMugRQR9DbPLUxilzjU/cS6pCieqYJ71Ho/pEFLujMGbZRXp2pRllpsLhTwAKBVLgY4x6jxf3VbgrGQXAbDzI/PFNR4Yi/ZqvY4aP0RT4xpn6j1PvEU7y5+QGe7hixJE3FrE=,iv:uH0O4e3X3fBxwVejquXSHomgWi+0yGim8FCcXVMJN38=,tag:HF+n92VYx48Xx5/gTmcbJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
