apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:GP1xrZP8raz35qVT/4XQ,iv:Blk71gHnU+KOXNkL+N6K3efzjARnWRivrQcNLw0w6A4=,tag:2oVhnYVlFQpu2Uk+2xf07A==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdmNNcnllakFYaElvRTJ3
        UU5CYTNnbEhWL242TTEzbnFXaXR0MzFSTFdvClNTb0FSQjFGRUZHS3dPTnR2cDBO
        cEFBb25PSEpXWVozZFRVSjA1TDR2cUkKLS0tIExBYmY2WVE5NGNLajhFa01qUEN0
        dEhVd2ZDT1lOaXlRSVhVZ0FyM1RIL3MKVo7/EVW8pdNtsLEVnO86+NKyDj7g8l8y
        cgP5EVxsqPGGxJE/vyj1BaU7A4/uss6yIMjeBM+Aqs4ydzE4BLj/4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:33:26Z"
  mac: ENC[AES256_GCM,data:iihppjJJP9GbGRPLJlnH2ZJt1QsJA5UpyOEPKvp5m8RkUR9lQLAItqUjXbNl6xvLyPEdCJEdZqlUdm8xDOwpITPQ3AnQFhHZluHcGAbUBL15ilqUmc9KzEpNXfvIqW4UVCyzaP93M3vhvYKW6GHtptCrq0rQPdGZMW/Vit03lLM=,iv:ScHHPdKDHJ0isopLqudYaWNBAipaQQRECrGNfrEMO0g=,tag:kh7ABIh9l4wpD1pfe7Gzbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
