apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:fXkFteTZra4NtgP/WKOv,iv:vm4wQPur8HBqT5EFlLx6jeacz8xy6GE4SBdHRMnuspI=,tag:Su5GnwU7GC7hEmhNMFMJFA==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPamt1czI4OWtiQnZhRGND
        cDE4enBseWxrRTdDTVRTYWJ2d2FzeWVCTDF3ClhYVWs1eVpJb09ubERrNC8vOWQ4
        Z3dxQUE0V0tLRUlPNWM2ZEd3R2NHcjAKLS0tIERBY0J3L1ZwSDQveVVmaDJ3blFk
        Z1BRUHVxdzNtUnpXeUlYci81VnJNT28Kvin5P7BXN3r/zXl46cKhBhqVR4raH+lL
        nJ6fiaFirkH5c5RL3mPKRyPTp1pjhp9y5EKw4W1MDC0jUYs102ySIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:24:06Z"
  mac: ENC[AES256_GCM,data:mtohECC1oET+3QYARrfyvbtokUpanWula3aM6KSuwTGOKJq5DJT4N2e2gQjXhBoDv0YdlpISfT6U/5DjJu81EC0FJpNS35SBLD+MAKzawLWwaIMR+K0NMJoT5CvpM2trD4d3RPl40tdHeT+YIMQKbm8UZAcGj5wY/EMhzWjupDE=,iv:zsVioP6E/d8hL27F3hLhMOP3X+ZWRb/RpGBo8x26a0M=,tag:tfnE57ney8qiTQh2PhXZAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
