apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:U8F9dWC3WnxIl7kJSFmJyjCGPAqIyYaCtgFCA4mW+lw=,iv:AkfSHtDGH4mIGctguhMjrPUtEnuSvBrZDfyXSenavqw=,tag:sWX0sWkslbaxsH7E5k7ouw==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaWtubC9ZRmxHUnZkWVcv
        eExYM2NPKytEbG10NUVsRURxREtPRmU5Z1VBCjRtczRIaHFhalphOTZuSTRRYjJu
        dWdJOVpYVmpSYm40aTN3NldyaTVVeXcKLS0tIDNaYkpiY1R0YnRzRFNZVGVJaWVx
        QVBZVUV0K1gyRnpURnVDaUoySlBhVFEKJmSn3L43LfGe8FkVfAYVbAkeTc4ROW2h
        DKaNTwEOmLKPFC0DuuRRSfeUgOS1GWkMqBJ+bVDmQj0Ql6T1DUKtDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:53:48Z"
  mac: ENC[AES256_GCM,data:DqNm1Bb072dtbfTaf3zL6o/nubewL/f9xgaEPiRaOTKKbPqRTfgqCo/J82Y/CRcGIa5jKCKYY+xG8wtQ0gPqeH+Nk5ffpzp44l35kf8scTGoO6cjXujItfyeY1bRpjVQYYU9pVxr09yK45kVsSTYQQZ1nhCYkFTbaKEf6Isi7hU=,iv:y4nKxfVWYav6UDOdWsNNtFE37Q8DK/bNgbgvk1xYyiA=,tag:2H/LNt1FPE6da3RJK4mneg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
