apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:DJB9bSi5C1HkmlHghvQfrtbIjUDGzxygL5+qiQHLgag=,iv:JOBG/bzQckC7hRYhpcJAyKgNS0KwgRsD6kHfxM2ybZ4=,tag:Hetlb1W+FKy36nT9XtuyNg==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVTdGTXVSY1ROWWdoU20y
        K3ZCY1RkSGhTaEpXTDRsNnRWbk5HRzRYMUIwCkRXcnFWWG42N0xFSGdpSEovdllJ
        N1doQnd2WHRXODAweEQ1MzBmUUVWdEEKLS0tIFlyc2xwUW1uc0R1NCtESzVQN29C
        dUxJYWtpZDlIZFZheXZMUW93V1lEL3cKtargqKxLlTwW2i5DmgunsOXkY60jYkSh
        ngRlu0QAsr6aiH5PRb8hZptAynbVCws/UFI2ddit+7BnkbXTZeKfsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:00:43Z"
  mac: ENC[AES256_GCM,data:XNda/dYfgh8vWk2FJlNub57Rf1vlND4rDooOew7zhGPr/Zx/65KMexpCClLw5uw7ZrBwpM/E0/rBza8Lvd47ZaletYCOoOzjOIqKB2E2zuCtRG3lgb10MgJ/DVdSF0hRb7k2ILCAfR+XnzDzM3a45b+rNp08OIEhll8mtpLgiAs=,iv:ykDFp85A79odRBg+lgpdqM31n4auCAD8Z6ISUub++ws=,tag:wd5xAyJyvJAD7uLaXzVMlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
