apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:1vEy0tqyKxTHlqdsPTwE1ft3gGl/4d0kjWmiwP/qJqM=,iv:DuAW/wEyJZifkk+CTUweQOb/uTzaJrr6foOY0XywXoM=,tag:VOYW2aoKkCHq71MFyRuZHg==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSnhRODYwRWVjVGtOUGpq
        VjNpd25HQzl3SW9BbVlySktmVEFDb1B6SmtnCjczM3ZXNVlpMTdhdkhGblgxMFpQ
        Q1lnZzdSTFM2Ky9Pd1Z6MlNUL3R6Y1kKLS0tIGZvWEpoLzlqa1VBOS9Da2FLL29n
        UE1lZVc2R3NmZDRHR0pyb1NWcms0NG8KzUzhNIrrJK1L6cpjPQDMYVrfDA9pLYQi
        /6GaiYa4zmSQ4/AKt58wMnkaYDeRufsL3B/nRDfRVQqcjwXp2VvTRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:24:06Z"
  mac: ENC[AES256_GCM,data:0xfUWVpLCvioXGPekOL5QVOS4/gB6zSrp3dBFRZU+yMnZD4xOGA6BA/1KSxgCYT4YD+xhxeqflOSGxPTtunEUbL2ZC21N8SfyzwGODPJpGckUUSOoEsCajIwyAZVCBTVADqdbSz5eMptClUTc5cgHJjYScgVJOqrULoLRrSjzOI=,iv:5n/c+YDGFSwBuVxcmVPAK7T6qg1KmNMDJwZDTPdPbms=,tag:9ntKs0Dc8CJ22PZhiyn0tw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
