apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pvpiHH6OgT48mohwrOoFohvAjm7rAxzBr84aOhHspOU=,iv:NSyED7ISJyeVx/AtHsjMq5YV8NWL2LvJWYOZEnpBCVc=,tag:6Ca+CQDN448uChbRwjA67Q==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bG9VKzdENkpDQzk2Rmh2
        bTA5Q3paTUNaNjl4NXgralI3V0JhNWZKbFNzClZaSnRMaFNJakVwVlZqRWNxQUFH
        eTR6a1dZcnJhNFl6S3gvVElBWG9aZ00KLS0tIDAzUnBjdHd2cDJqa25WOTRIWTUv
        NTdzMUg0NDR1LzBFdjZ6ZEtlNVBXZFUK0UAGRZE1RsBMkk7uVnAnVTMBoacQsT/w
        DEH5etkjoSu0qi50CaR1q0KDWpjtCfrBUOBTEAeWtDHLJsN8/xaEew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:31:04Z"
  mac: ENC[AES256_GCM,data:XMrNGeKaNh7s4BtZ1gzv/dQS8LNfw//wc07lN2PIGJF/X5aQGsvc6PjLs2wMnO17Mkkb2mdzeaRtks22UnoZcQwFJaGqqkzOX6he4XMEoGgxpChD35JrgUn6ZKsQ09llof7pnkMCsxn5DXR/Hj7g48fY58rfkKIY70Tl8GqZy78=,iv:YaOiQ3HchmSo+4cXw324bvwBMLH5yTT7bcZ6FBb2eJU=,tag:PPQRkO7IBbGIJxML+ZhmPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
