apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:zvy26et+T/6zDJ4E0Rg9e07ykbIfqc0qIGOoxCOOJBk=,iv:pUOYxZgBmcBgP6e/nqHSNByp9PocLYgmjZvtqoKBUxs=,tag:Pk8COUlAcE7rA8o29sVncA==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRmVIUWpwYmZHQ1gwTGpY
        ZWxRcDkzd1dnd1hkNkZuWXpBeFB2NkEvQ21JCllQTEpGUVcxVVJIbXpXTGpwYTBX
        L1NBTDh4TGc4U3RHM2luQVlnbjFacEUKLS0tIHlBNHJCbmZFaCtiL0tCQVlpY1pC
        M1dNTVJjUEFqUFNkYTVaMTFhOHh6QlUKPFI5k/f/bm9YeNq9udfajhSN43oA7mwW
        2lSqGp66L2XtE4MhTDDl6x+HtHeyAeId3jOUuBGHTLALoVNUG8Hpsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T10:27:58Z"
  mac: ENC[AES256_GCM,data:tpLmF7kJlDpaP3W9xZIb2EoACbwYNn/JQ4kfrAlwtyp8s5YJ7c9KYxW7K8rKEfBFbEeg8AhMebTmcSlrM2isxuSkf8SfqsT3lq7Csk5mcldpdTpnrpmcQ/2qfRsq+PA01kRpM8heVnWqZupVSG5o8R/8bCHEk5GdwZqflZbJvWw=,iv:jlWow52mC4FRpqMHPQM/re3hvbZUMl+sal/1tCTHuzc=,tag:Ol+qPpGYbriLFmX70oNOyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
