apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:S/ohn7QgClArW9kAc0FGxpZhv58HTcVzYJZkcFodi7g=,iv:KRJlDDzkun6yojIILJ6I1n14rYPrtHD/SwM955/BcQs=,tag:A4+1Mj0mzJkn/IbmRH8p1Q==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOM0o0ZlBzODJQYzdTVWN4
        aW1LK04vcmxVbFg5Y3ZHVk9EaHhWYStOTWo4CmJDSC9Ib0xNVVE1eURtTDkvMlM5
        VjBKT3ptbWdjVlp4bGs0SmtZV2QrRWsKLS0tIHUzdEJKcDNCYVVTSGxGbnBuc1Y0
        MS9sUEIzVzBCQ0dUSEI4d0JMYTFYWk0K/Jlwzv7L50+MrOKrJ6ywB/6aRHp8Mk2K
        EfAiz5nyJAg21Xy2lo3gjOs2rVxi3i2kBGEV1rka+QvVaMl57o8WdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:33:26Z"
  mac: ENC[AES256_GCM,data:zIK6S396/2/GAs/rpzoM+ng3xkiFpJ+1I0HANCqJBSAvodr3pj270esOgj7vuIyaNAJh4vRx+W0tWY4BHVJAVzn2IsYHinNr2lnQpR3Nh7FwsRKByJxckmUuAM/tYt2r/x3fP2pELmOXvnAIvwCfaema1MlVrQ4+oMZFfNbIcL4=,iv:LWJUpswbC8UFW5487Udt7EvrjxrKa/pQgb8/i5RO6js=,tag:Cz1W24tX9tBkvQeTplGq/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
