---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./dashboard
  - ./ocirepository.yaml
  - ./prometheusrule.yaml
  - ./secret.sops.yaml
