---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres18
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
# Note: Bootstrap is needed when recovering from an existing cnpg cluster
  bootstrap:
# Enable blow when restoring from minio backups
    recovery:
      source: &previousCluster postgres18-v2
#      recoveryTarget:
#        targetTime: "2026-01-18T00:00:00+11:00"
# Enable below to import from pg17
#    initdb:
#      import:
#        type: monolith
#        databases: ["*"]
#        roles: ["*"]
#        source:
#          externalCluster: postgres17
  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 10GB
      shared_buffers: 512MB
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
  monitoring:
    enablePodMonitor: false

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: minio-pg18
        serverName: postgres18-v3

#  backup:
#    retentionPolicy: 30d
#    barmanObjectStore:
#      wal:
#        compression: bzip2
#        maxParallel: 8
#      data:
#        compression: bzip2
#      destinationPath: s3://cnpg-backups-new/
#      endpointURL: http://192.168.10.198:9000
#      serverName: &currentCluster postgres17-v3
#      s3Credentials:
#        accessKeyId:
#          name: cloudnative-pg-secret
#          key: aws-access-key-id
#        secretAccessKey:
#          name: cloudnative-pg-secret
#          key: aws-secret-access-key
# Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: postgres18-v1
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio-pg18
          serverName: postgres18-v2
#    - name: *previousCluster
#      barmanObjectStore:
#        wal:
#          compression: bzip2
#          maxParallel: 8
#        destinationPath: s3://cnpg-backups-new/
#        endpointURL: http://192.168.10.198:9000
#        s3Credentials:
#          accessKeyId:
#            name: cloudnative-pg-secret
#            key: aws-access-key-id
#          secretAccessKey:
#            name: cloudnative-pg-secret
#            key: aws-secret-access-key
#    - name: postgres17
#      connectionParameters:
#        host: postgres17-rw.database.svc.cluster.local
#        user: postgres
#        dbname: postgres
#      password:
#        name: cloudnative-pg-secret
#        key: password
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: kubernetes.io/arch
#            operator: In
#            values:
#            - arm64
#      preferredDuringSchedulingIgnoredDuringExecution:
#      - weight: 50
#        preference:
#          matchExpressions:
#          - key: node-role.kubernetes.io/worker
#            operator: In
#            values:
#            - worker
