---
apiVersion: v1
kind: Service
metadata:
  name: postgres18-lb
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres18.davidstewen.com
    lbipam.cilium.io/ips: ${SVC_POSTGRES18_ADDR}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres18
    role: primary
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-r
# spec:
#   type: ClusterIP
#   ports:
#     - name: postgres
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres16
#     cnpg.io/podRole: instance
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-ro
# spec:
#   type: ClusterIP
#   ports:
#     - name: postgres
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres16
#     role: replica
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-rw
# spec:
#   type: ClusterIP
#   ports:
#     - name: postgres
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres16
#     role: primary
#   sessionAffinity: None
