---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
components:
  - ../../components/sops
resources:
  - ./namespace.yaml
  # Flux-Kustomizations
#  - ./audiobookshelf/ks.yaml
  - ./esphome/ks.yaml
#  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./node-red/ks.yaml
#  - ./smtp-relay/ks.yaml
  - ./unifi/ks.yaml
#  - ./vaultwarden/ks.yaml
  - ./wallos/ks.yaml
#  - ./wyoming-piper/ks.yaml
#  - ./wyoming-services/ks.yaml
#  - ./wyoming-whisper/ks.yaml
#  - ./zigbee2mqtt/ks.yaml
