apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1PG1uk6gDOlX5HsWgA6prLyRuTTV/qi1JIlTLM7V0Tnt7GitsoBsICC+UmUIJNXOe+FzdVsRuKVaKZ+mRdR3JFtT1BQt/XOJuRVSQGuzjJveqhspqV9+v52E6twr4n9xYjQFDHFKvogdmA706v4S/HTSB+sUxEZt+nKzM4YVkaeO2rNS6kMVkx0ZrpWWlhDNoI+9kgBLb61xoqQlYwIn8sPr2/16Aa+mDnd8Vy1E1ARPNW2B,iv:IUaCFDAPyuUqIBY07GTd0GiuMGREgkciUY5Xr3mlZdg=,tag:ktfuRujLTmB6fvXBVIrkUw==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNU1TWDdwYjRuUTZ5aGMx
        djlwRlNjelBzL3pWKzJucTNRbUFJRk5RK3g0CkwwcXFReVlvYml5ZGlMQ21KZUZ3
        Qm9EYnl2T2VCZHNoOThYYlQ5STNCbE0KLS0tIDMvZHcvWUl2VldVUzg4aGMvdUJT
        OFJCeXBsRWo4S0dWQ2Yrcy9HVUR4OFkKu3NzDpIKgQ0n0jNd/MhXxkn61CG0xZ6J
        V6LxPGdtKMTrZSb1YVSc0Y/DezzrtRZG9iUlZ94NqmzDTa5TDSg3Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:53:48Z"
  mac: ENC[AES256_GCM,data:unTNi5QUBzNfOXvX7UCJjI3d8OwIrShLaIhdO0JEce/h9SpoeCH4M0py7CfeGyemUuTAN/iUDppr3aiPclfH9pu1sQWNtx2Yq7GfpCAe5M4X8slKF3kMOjiKUfKcw7YmVkgnR7YP942xNCqcudpIXcxXIgGiqhPbpmyd48cFrJg=,iv:HKsnGumS5LgsDevjJtbFMAghtJ9YhH9MlRU/2+ifkWc=,tag:RtyhU9hwgOiT92iCHiUPfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
