apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:tCgsNZq9ZTCCWScXZbb1RiUJyD6kbzp/zEzKffeX9H0wk2GVWzt/OGAdfTLzi9nJuicbBHFZI4EXUei/aWdetF0pKyfcrj1UKlBnQ5putN+pvT7iQ0u2EMl7Rng87K8ZzLYFyI3/TA3SG85vzDt3bK03a+iERT1EM/1ozfAxI9MIZ0GYrJdnsWkk7yXH9H6LVItePWm9e1Lnth/idOiZvNzqcirVFRcmv7NFllV4zgXI8xTb,iv:GOkbsBNYfAC9l1qGtrjau7atnm28wJheyT2Nz4gav3U=,tag:gju6nWQns5vaY6D0LbB+PA==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUTJiTzhVWnNBYW5mL3BY
        Q2YvZ2IrK0d4SmpKbzdKOEZlb0kxcCtNeWx3CnMrZ2NBVWJHalBVNnFaSS9Jbjg1
        VzBLSVNqS202bUNrUWZ3ckNtVHk3UTgKLS0tIHZPYWxIbUQ1cUdmalphQjI4VWJM
        TW8xdUplVEpjVFY5N05qaWxKczlidWsKn8abVwQ23aieSsUasOBKWlyPQRKg1XrB
        ovq0MQrnMGrYGA+gJpb0PKBBNtFZmhgAQ8o9ZomqxDGIZlJfHKXmwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:33:26Z"
  mac: ENC[AES256_GCM,data:DA2NFkppmQlXT8AUUbBOjeEGawjcImEme7MVbnp+tyq/peL6ngnaN00iW4CNUwTgK2+LSiSf7I3OLolbrOFqp8XpKqwFCWIJ6QoCJ8ex1KQ23ywsMCqB/3OIFM+Fo+lJfwqSH52jua9ARLc+oSFHGzu46oc079xAzntETDaIpOA=,iv:nPN7+JqpWNNZamm/SMlFWVDr1C2UN6DhmqIoZoiyfEc=,tag:W7BM1KBkGzwLMm1znCem7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
