apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:qzwxdKreYX0+7YEaIiyMUQUWGdk3La9TGPDCWesHaOoPVFEJYIWz/pB3PVVGT7rfI3q5onP3J3vQpQckrf27C9UFFhB5ysKVFEWvtOtlnWXNoh2fQyY1bmzVMkNmZju82xWJDiTLcF/z1iNFhhWvYQeUcOoOf+NB6Zp/taYDiiiiqU1yrUi4307Lug+KLDqonPr9k26GySFS+RXDmrs7xLXcDOOzkM1ZFpNerbi9TI5dxwkk,iv:UmpPf2nb4pX1ve7vAoD/bQCk81+j5BidPz2edycSQIA=,tag:GOCXyIcU7uvMjAIS9ZNltA==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdHBsNHloZDdkVmtWMS8y
        T1E1M3BvRGU1c21qRGJmSHVsVm5wb1ErV0FRCk54K3RxYStJN0l3U1dQTDFIZzFn
        Y1pYQnJyVFZLejlrMzlaUWJFWnVsNmsKLS0tIGpZRUV4RE9kN0Y2RmxoWjU0ZHZy
        eFZwM1lOZ2k5VGd3RysyNk00Yy9hVkkK2z7nYKVG1Z8vFDDBCOlAAZg9i3v7x1RZ
        VGCIYhbgH1DOWWWzYkC9razCUCqGWSBnQ7m+/Z9zOGlAdF95zv+TSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T10:27:58Z"
  mac: ENC[AES256_GCM,data:F/nyjR3+XWiCyxwFv8n1s82cFw9MK0PuaCbymRxfnL6K08q8Q64LXL+mObFQLBKlJr/AS9Ku9/g3tehJrxDp5J5ZxbeK8B2qj0S/oBki9OCjoUJjxnxFHZicU0n4ni1cRHqa6wIHykVYOn3/4jJe5vEucNHnpONs5u39raJhhZ8=,iv:cJSNeijL3//7Y4zBSAeTcTG71OU+XOh9/dnWrOCpSw4=,tag:AoTfnds8dSRS81iUtyPDVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
