apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:5itPHxMm4ImtgNIHJgZE2Si45jf6Br0nEX/XamQxJezv9dbW32kr8DzROCuBj/ZSRQeK1KVxoZ+HxFDRUVZzp+0mZGzbVwo3RYUSWxLZKnaDHNwmbfZAs2spR07A1JpCmAVGoQDEeOjjjL+kNimRPS22eQLhjxaKs8MV0N1RkmiQUcaMXSf3kw7yU2hkrnDaOq+BsCA5J0y0W00WdVWWcU7QTRF0OzqmMRPUOWD/w2ZS77gk,iv:N8+raxbh36urxuTiy0/Q+eN6MlSP81ZGbvH61g0GU+8=,tag:KUym2C0FxxbNNBt36Xj54g==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NHROeW9zSHllSGVOczZj
        TlJvSmhxbzNIK0U3d1BCTXFRY2FOeU9wQ1hnCnZ5QVlubUljTksyb0YreEVNLzVI
        R1RhMzFQMS81bFFyRmNZOXBZWFdXWUEKLS0tIHR1RGJRRmRMRUtYQzhZMFF1MDE1
        WUxqVjFGSjBnSkZBV1BJcllCNTc3ejAKODm8Oz0F15nZNv/xDdMm1e+LXrG2HXBG
        6kx3m71bt/Rtl1Mx5PB8zRBTy+2jfRncDVIC4VeQTvUumjaHakRXrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:00:43Z"
  mac: ENC[AES256_GCM,data:RgqHLXfYMxmH/Y2JRFt4mhlis/grZxxWwXy6dqcoXnjsreE85hlpNUsY+UCaBHaFz1r8CrKstf5QMXA8RvSKya+GUzWxKQAKMwGJ+YdQg48D17qTArML9NoRZbMOyFMWGsGWucrHCQi610KYvwhfal74wDcbWoMcFmBuPx2PdRQ=,iv:ZuPL2QpSi9eAiO74SW9vy9rquxbSHwe/WEaZxsB5eAY=,tag:wPKOAXtPaiMQsho+nOGZng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
