apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:MxVYet3k7wJa0IZiw/GoKlGx78Bx76DG+IJayeF1Rmwmf46DxeqJ/mTxhuCVtxkrevjqKyTownttUEV/Q0TCvXocW00wdP0ugRYh7/Nc6K6TMtfls6NEh2H5zk1FFNyz8xsgwcH0vpd4uZhYUwDg2nnvTlSRw3I/3eyWt1Y7WE6XYiC5/y/LjB7rz4fVkbp26FpeJAoRWWqmAcFPEFihMa2aAUWV9fsJAmmEkGyKKMw5z14m,iv:enSLBH/qJDzsjgVmbei6pZ1tTX5VizNWTbIbgw7LVlo=,tag:Cig+ZEnYKFXsVBGQ2enwxQ==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQnJpM3NiODFuVlg0bi9X
        OS90WnVKUi94L3hCTEdRR0tmeXB3dHlBTmhVCjJyR3R2VG9NR0REbGFDM1FWS0t1
        eVpJVng2Ym0vczFLTVZyUkhVbFk4MHMKLS0tIDZTTjJKRDRxZHF4dEp2SW0vcXZ2
        S05WSHN2NSt0bExXVnlsZ1VrUHpBaFkKonLYy7zzUPKgJanMSX+k6x3s5x0jr78u
        90o6Mdg4wjmZPQQns4o7OK0RHp4t3xhCmIwg+LihQa5KWQI0Zmx2sw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:31:04Z"
  mac: ENC[AES256_GCM,data:GrMRoRrzGXvFibQLV8gKRYE915oCh26z4C11vc6UMX2qPA/y6YWN27064PCzLjiKDR9ksGsZeEnQckY258o02xU0I4opoV4Zy7MJQjo069djHvIH7hBTBMMW7FpgnJrH7B0bBmqBa3fMKjQo45s1shWEHY3o/JiCAUBhsEpm1Qw=,iv:OsYjG5TAAPZL0Hz/OdWIbjRIpEbjFbNUxjx8b4qAA4A=,tag:Q2+jIR9FdV/fz1BLhAaoZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
