apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:vV7O8J1sFbgiU686dmj3GJAJMnzPXSsLRu2DmMv1F5GDc1hN7hdS4HlNxb3yClKM62EVh6ZFXUZXPmvpEphYhI5YhKZoMGJZwVBp/sXH3ehHrCgvlQC8TMUzUQVPYCKLtVqmdXMG1lBqposbV2VZj0znQiqBX2d5gkZttoPq0ithgBK6Qdw5GAaUtY9udf6Rx/hzsy1Jz1TnBn0MGPzX6HWttlMcWhFLWVFYHncezRxJzlWa,iv:UkBYZcnNQybR0RO19QEKC32VzBY72MS5XK2t0YoDYx0=,tag:sAhtBjWLcnPaXD/tV09nrw==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvb3dJNUNJaFN2R285eXJH
        OVhYSWNweVhCaitCaDFTMVpFNE54ODFOSVRvCjRwMkxSU092eC9rMVJ2U01CS3c1
        YTFCaGE2RkVmVnVxSWswdGZ0eWJjNEkKLS0tIGFybTNXNGRMV01YUlRHd1VQOFlt
        VHZmV00yQzBDNEF3dElrT245VGhvaEUKjNsHvFFBrvIony+prkukhHFc79tTrRLy
        L90dmjS7Gs2fstWyXYC5o1psu7EcrI6jKg7bx4v0oce/e7p0nhUHag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:24:06Z"
  mac: ENC[AES256_GCM,data:xKk/Zj+BZWd/9TNhYs365t3RNHQt3Qu21F7t//zQuRuEOPoWG4N8i7E7koeYGpYGtAKyr5jg5u5vTh57v9gjmua5YT9Z8G0TCfu/ha0L9MYA+9bVc/YlXNJWAI3Wrdj529LFIOJK+/ae3+amY45yq21uipO7sgC83d0F83wEJgA=,iv:1IoG9oLSQDkpDSsx0P676CWNdAQUYG9o7jgHAMys8Eg=,tag:mZ2MnYr4naM1V0TWGUvxIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
