---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nextcloud
  namespace: &namespace selfhosted
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
#    - ../../../../components/gatus/external
#    - ../../../../components/keda/nfs-scaler
    - ../../../../components/volsync
  dependsOn:
    - name: cloudnative-pg-cluster18
      namespace: database
    - name: dragonfly-cluster
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  targetNamespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/selfhosted/nextcloud/app
  postBuild:
    substitute:
      APP: nextcloud
      VOLSYNC_CAPACITY: 100Gi
      VOLSYNC_CLAIM: nextcloud-config-v2
      VOLSYNC_GID: "1000"
      VOLSYNC_UID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 15m
  wait: false
