---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter-t1500g-10mps
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: snmp-exporter
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    fullnameOverride: *app
    image:
      repository: quay.io/prometheus/snmp-exporter
#    extraArgs:
#      - "--config.file=/config/snmp.yaml"
#    extraConfigmapMounts:
#      - name: *app
#        mountPath: /config/snmp.yaml
#        subPath: snmp.yaml
#        configMap: *app
#        readOnly: true
#        defaultMode: 420
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 32Mi
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - name: t1500g-10mps-0
          target: 192.168.10.20
          module:
            - if_mib
      path: /snmp
      scrapeTimeout: 30s
#      scrapeInterval: 60s
      relabelings:
#        - source_labels: [__address__]
#          target_label: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
#        - target_label: __address__
#          replacement: s3700-24t4f-snmp-exporter:9116
#    nodeSelector:
#      node-role.kubernetes.io/worker: worker
#    affinity:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#          - matchExpressions:
#            - key: node-role.kubernetes.io/worker
#              operator: In
#              values:
#              - worker
#        preferredDuringSchedulingIgnoredDuringExecution:
#        - weight: 1
#          preference:
#            matchExpressions:
#            - key: kubernetes.io/arch
#              operator: In
#              values:
#              - arm64
