---
# yaml-language-server: $schema=https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres17
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres17
  podMetricsEndpoints:
  - port: metrics
