---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: minecraft-ftb
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.1.1
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-ftb
spec:
  chartRef:
    kind: OCIRepository
    name: minecraft-ftb
#  dependsOn: []
  interval: 15m
  values:
#    affinity:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#          - matchExpressions:
#            - key: kubernetes.io/arch
#              operator: In
#              values:
#              - amd64
#        preferredDuringSchedulingIgnoredDuringExecution:
#        - weight: 50
#          preference:
#            matchExpressions:
#            - key: node-role.kubernetes.io/worker
#              operator: In
#              values:
#              - worker
    resources:
      requests:
        memory: 4G
      limits:
        memory: 16G
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    serviceAnnotations:
      lbipam.cilium.io/ips: "10.200.15.230"
#      mc-router.itzg.me/externalServerName: "mcsv.${SECRET_DOMAIN}"
    livenessProbe:
      command:
        - mc-health
      initialDelaySeconds: 120
      periodSeconds: 10
    readinessProbe:
      command:
        - mc-health
      initialDelaySeconds: 120
      periodSeconds: 10
    startupProbe:
      command:
        - mc-health
      enabled: true
      failureThreshold: 60
      periodSeconds: 10
    image:
      repository: itzg/minecraft-server
      tag: java17
    minecraftServer:
      eula: "TRUE"
      version: "1.20.1"
      type: "FTBA"
      forceReDownload: true
      ftbModpackId: "119"
      ftbModpackVersionId: "12252"
      difficulty: normal
      whitelist: "dneck77"
      ops: "dneck77"
      gameMode: survival
      pvp: false
      onlineMode: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 12288M
      serviceType: LoadBalancer
      loadBalancerIP: "10.200.15.230"
#      servicePort: 25565
      motd: "TurtleTest FTB:R"
      externalTrafficPolicy: Cluster
      allowNether: true
      worldSaveName: TurtleTest
      viewDistance: 12
      overrideServerProperties: true
      modUrls:
        - https://github.com/cpburnz/minecraft-prometheus-exporter/releases/download/1.20.1-forge-1.0.0/Prometheus-Exporter-1.20.1-forge-1.0.0.jar
      extraPorts:
#      extraPorts:
#      - name: metrics
#        containerPort: 9225
#        protocol: TCP
#        service:
#          enabled: true
#          embedded: false
#          type: ClusterIP
#          port: 9225
#        ingress:
#          enabled: false
#      - name: map
#        containerPort: 8123
#        protocol: TCP
#        service:
#          enabled: true
#          embedded: false
#          type: ClusterIP
#          port: 8123
#        ingress:
#          ingressClassName: internal
#          enabled: true
#          hosts:
#          - name: &host "mc.${SECRET_DOMAIN}"
#            path: /
#          tls:
#          - secretName: *host
#            hosts:
#            - *host

# Open port 19565 for minecraft-prometheus-exporter
      - name: metrics
        containerPort: 19565
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 19565
        ingress:
          enabled: false

    persistence:
#      storageClass: local-hostpath
      dataDir:
        enabled: true
        existingClaim: minecraft-ftb-data
    extraEnv:
      # recommended rolling logs for saving disk
      ENABLE_ROLLING_LOGS: true
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      FORCE_WORLD_COPY: false
#      DEBUG: true
#      DEBUG_EXEC: true
#      DEBUG_MEMORY: true
