---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-containers
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: arc-runner-set-containers-arm64
    githubConfigUrl: https://github.com/dstewen/containers
    githubConfigSecret: pre-defined-secret
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: dind
    template:
      spec:
#        affinity:
#          nodeAffinity:
#            requiredDuringSchedulingIgnoredDuringExecution:
#              nodeSelectorTerms:
#              - matchExpressions:
#                - key: node-role.kubernetes.io/worker
#                  operator: In
#                  values:
#                  - worker
#            preferredDuringSchedulingIgnoredDuringExecution:
#            - weight: 1
#              preference:
#                matchExpressions:
#                - key: kubernetes.io/arch
#                  operator: In
#                  values:
#                  - arm64
#          podAntiAffinity:
#            preferredDuringSchedulingIgnoredDuringExecution:
#              - weight: 100
#                podAffinityTerm:
#                  labelSelector:
#                    matchExpressions:
#                      - key: actions.github.com/scale-set-name
#                        operator: In
#                        values:
#                          - arc-runner-set-containers-arm64
#                  topologyKey: kubernetes.io/hostname
        containers:
          - name: runner
            image: ghcr.io/joryirving/actions-runner:2.332.0@sha256:c5ead7730fecd7d7571fb00b6a43bbc8185e8233d29011eca2d9bafd7ad78040
            command: ["/home/runner/run.sh"]

# Required for arc metrics
#    listenerTemplate:
#      metadata:
#        annotations:
#          prometheus.io/scrape: "true"
#          prometheus.io/path: "/metrics"
#          prometheus.io/port: "8080"
#    listenerTemplate:
#      spec:
#        containers:
#        affinity:
#          nodeAffinity:
#            requiredDuringSchedulingIgnoredDuringExecution:
#              nodeSelectorTerms:
#              - matchExpressions:
#                - key: node-role.kubernetes.io/worker
#                  operator: In
#                  values:
#                  - worker
#            preferredDuringSchedulingIgnoredDuringExecution:
#            - weight: 1
#              preference:
#                matchExpressions:
#                - key: kubernetes.io/arch
#                  operator: In
#                  values:
#                  - arm64
    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: actions-runner-system
#  valuesFrom:
#    - kind: Secret
#      name: actions-runner-controller-auth-secret
#      valuesKey: github_app_id
#      targetPath: githubConfigSecret.github_app_id
#    - kind: Secret
#      name: actions-runner-controller-auth-secret
#      valuesKey: github_app_installation_id
#      targetPath: githubConfigSecret.github_app_installation_id
#    - kind: Secret
#      name: actions-runner-controller-auth-secret
#      valuesKey: github_app_private_key
#      targetPath: githubConfigSecret.github_app_private_key
#    nodeSelector:
#      node-role.kubernetes.io/worker: worker
