---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui-pipelines
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    timeout: 15m
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:

    global:
      fullnameOverride: pipelines

    controllers:
      open-webui-pipelines:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          labels:
#            egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place
#            egress.home.arpa/internet: allow
          terminationGracePeriodSeconds: 600

        containers:
          app:

            image:
              repository: ghcr.io/open-webui/pipelines
              tag: latest@sha256:b48e9bc338ce2be0acfbeff01810db72408a12f07739f9e3879c1f2b00952d6e

            env:
              PIPELINES_REQUIREMENTS_PATH: /tmp/pipelines_requirements/deepresearch_requirements.txt
              PIPELINES_DIR: "/app/scripts"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 9099
                  initialDelaySeconds: 600
                  periodSeconds: 10
                  failureThreshold: 40
                  timeoutSeconds: 5
            resources:
              requests:
                cpu: "10m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"

    service:
      app:
        controller: open-webui-pipelines
        ports:
          http:
            port: 9099

    persistence:
      conf:
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          open-webui-pipelines:
            app:
              - path: /app/pipelines

      pipelines-requirements:
        type: configMap
        name: openwebui-pipelines-requirements-configmap
        advancedMounts:
          open-webui-pipelines:
            app:
              - path: /tmp/pipelines_requirements/deepresearch_requirements.txt
                subPath: deepresearch_requirements.txt

      pipelines-scripts:
        existingClaim: pipelines-scripts
        advancedMounts:
          open-webui-pipelines:
            app:
              - path: /app/scripts/
                readOnly: false
