apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:SQz3KI+YHkw4kiiIGUTdxEQ4lTlOGICCAEpcuC2RsU/Cv8Uqp20yRw==,iv:5+Ua08bRr4zrsUDS1a8WkQVTHEgXz9aaGw1w64f83y8=,tag:uWwrVugwokQoBJ70ARGBGg==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQUFsZUVUUVcxbDR0MHUv
        bmgzZGwrcWQ3SEV5MklpOUgxOUwxMWg4RW44CmVlZEFwaTBWcEV5R2JtVzhINXpJ
        UHRSdFRHRW00NmJZbFplbkZ1bXFpZUkKLS0tIHBML20rdTVXWjczUFNwNTZWZkhI
        VlR0RjgxNWpYeGphMmpYS2J6MWQ0NVUKqpIUWLE81XM6R08st827py7c6uSHlaSj
        FU0z2t8UE7nktT0rmg47bA1py1Ci02twnBSq7oNBxsNOxg8b3dQBMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:33:26Z"
  mac: ENC[AES256_GCM,data:37BcHzpwUtDBkqWroE+Tl2pi6nIWnf/Tuf4yEu0Gw2VAraxL3HPpljG/vO3ZO43sgLdE2LfZzS2BFV9r6retTscEnEhj34CRhwdlA8iFrcCQAZQ3jfyya77lLnTL7iEhapZIqKfkWfAYOJDzJdVQEALYUdaivFAUeBWyMVEvPVw=,iv:Ztw3qvH0AaP6OG5g8n5YOWT4KFDAbeUL7/8HDwzAleE=,tag:dHeqraV9Bvle1WFoham9Gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
