apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:3NQoUTLu/kkJlt4I2qVIbIEzXzsqGW9sgqbZxx0VRXt+x16FUc1iCA==,iv:27xfywIU9AM6JYpGIGKNfVONLuFT0MKeO78qozJDQts=,tag:SuxoBiQ/7GUrxiQDMPF+5Q==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQ3JVSnVibk93c3B1ZTJP
        Q3RTVExsYWIwc0toalRNWFNUVEZDU0tDSXhFClZPQzlHYlpFdUFTVUVCUm4vdHEy
        eE81WXdIMFBScEt4dnMyN1V1dnZiaTAKLS0tIE1ITkJLTTgrZDNEcm1NVXNTa0tF
        Y0Fja2V4N3NnN3d4N09oMnQ3T2JCRW8KJAeth7vChtqvYnMdkz1xxNM2nZ+y6rtn
        c82t28xjeWNWMqQ0rRWIEvqcZAoS73c+Hm9eTlDywjMmF/g/FtAHow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:31:04Z"
  mac: ENC[AES256_GCM,data:PZbDBqgGGRfAvbPMpvzqX4jlodjOqqPpOf8zLK1gha6NbVndvfv4d9jKnhfSzpYjN8ye5ncJpz8fLHNed0ZrR/GReEMES9jsJiqhVvI5Q6AEpY5QyLoaNrWw1oYdLRPb1aVoDYQy+IDzg/oSREr2qAPAUZNM8pVPax9brrUjK4g=,iv:5vp15b64fo7R4nQDZX72/ff7Qj/O1nUWps2ns89pDGw=,tag:Docv5xpX4irtq56bIVLRTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
