apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Y25uCI+YJQwdvPWuUAYNXBZnOMgttdwsTpnqD6TVztTzEfRPBcaTEw==,iv:6cRmqQw8/F0H2/KNgNeCoozSilYyXOItRSIoWsWmkqs=,tag:Ci7581sYSd0zPuFhzPJ/JA==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuLy90K043eTkwZ1JpR3Vj
        cURCUytqaFluZUhNWUlEU004OFZzb3MwMEFFCjladVFyQUlIZXRGSm9FK0k0Ti9G
        elo4MDJaWFdteE4vUmZuOHNzNDk4NlUKLS0tIFZZMFB0YzFtNCt5ckFoSDVidlZq
        dU04NGt4ZmEzbi8zelVwM0hadzZzU1EKivPzImxFvNoyNYLM9s8/gkSkVGNproi8
        qG8jtSDXqMuBcUgl2UIei9Inj4rmhsOOZfj7xhJoorEeGdQmjrok+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T08:00:43Z"
  mac: ENC[AES256_GCM,data:YlhGr+UtoiESNA6c7HLPStvDfP2B9kSYBPQlAOe6281T4dNcHeppXH1Y1pch3ittUR37z9fNepKqRqHyRCylUapGcEoDff8QvbRCDRvbfpW1rgM/a2FQ4VTwYFGKdjCJZiVUD/yJizHVJFYEdesW1CF6T9w9KyHrCoKhKoo4yfA=,iv:bzcrY7w3z9a8MAuTQXSVViI5Mm/v5Cs9YMjeNeVxzLI=,tag:a53UpD6jC9rBx5H0RXooFA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
