apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BYuhPtCjplal6Z0Ti82FsiQTk/B2rV/IPJ0xWVVwtFqkIfITQ8361Q==,iv:/t1fKOi2FnC/BGgA/O29s6buKL8FlMkZkXJcWx1WNek=,tag:s3gwaXoyMvKzLfJDpyDynA==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Ty9EM2RTVEtnc3F1Y2Ey
        NU1uNGVUSmNBSzQwa0JrdjJjMXJmNXIyRmo4CnpQQVN1Wlg2SElmOGtPUmthVWVR
        dVNaWGlEdUFuZXFhUUhia3N0MjM3Y1UKLS0tIFJpV213OTBRS3pMazZreGhrSFBN
        eWRIT1FJZGI2emJMeUUzMjZRcHVVdXcKP8z+v76BRyMtJcDEwj0/Iv/ItoUFfzgJ
        5fcLdAfretZKf0dbPmrarxaXC+WxQsAxEMoDB33dQN9ygxqIYm0LRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T10:27:58Z"
  mac: ENC[AES256_GCM,data:iZnmdiMKRuBTBgqeQc+BiTSiYdGzg+e9n5GIvKXD8+us9M/Xba4jeJLY08edmjAvHN3gZQe+VhkA1tsJnA/AxvNPNN0VFmtK5Os5lLtRNX7hukozyhvTimrUiTbh9O3dL1Fr6EKUFqGTgukDIJJQJs6fGPcq8SghyUiKG6GWHqU=,iv:AhSbEptH7CADNzHUOlD+s3NZ4Mtxs97XIXAS9nQyk8U=,tag:tT3mYCnKSALngzU5yDjh/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
