apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:fsS+A9y07FYglLtumGxhV7M5c7ygCcjXrTa68iCQLnqgAsf3yP0mJg==,iv:eWI1S5/o17nsWn6fswxJ94qhnhj572shKvDUcKOjidM=,tag:JW9QoP31Li4KXkx2bFloow==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUzYzUVB1Q0Nab3YyaW5Y
        UEFJRHF6dzgzOUZVMm16cGMyTVZBeUdKK0hJCkMyamlIM3ZKbmhYdURPbFQ1LzAr
        VU5kOHlXWnpwMkxKZXMyd0xWYjlidHMKLS0tIENRWS9xNXYwSlpIS3orM1dmRGNk
        M0k2UzRKZ0F2OGI0d3cvUERUT3o5WGMKYFCl+VwE9p4HyMi9nt3hoNIQ8l6ged1h
        vSf6DPEio/CyLEVUWgnTtyS5k5EQP2iGTuKhel24YrGVHXcRZwkwNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:24:06Z"
  mac: ENC[AES256_GCM,data:cEErckF612dxY+h6ogNFuNw+ZG23fha1vUtL43ND77FMcOcVxChmpaLrQxY2UtAoCysd8jdwfnoc3VJJS7hefCW0tyAwpYlHWk/pj06djEFAW2WQ28RlxXrNm6kw1ZMdfHc3QQskSD2f2FJVEGmvvHY2zAya2QrfdTrSIoJ84bM=,iv:DTb3YHIlchlmdKy3VbpCsbNG9mlVzc0C7K9cG8n1F6k=,tag:6uxxECx8nvCyggdCZvys0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
