apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:OpzJgC/ixsnhKnJDHkLIR9/KDEuiUKpxcDx8rZ/LqLgqXZFA9Lyeqw==,iv:QxwvhHQpDJ4Ge9dVWRzFTKAzf1xlK3aFzJXnvTGoNx0=,tag:FAToRDem5eSy4K2Q/SOk6A==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVEZxamd2T1BnZndPZ2Zj
        NzZIN2ZPWDhhT2QvZ1owTFRjSU8rM0gzaG0wCnRmU2h1a2RvQ2pjejQvRFRaOWR4
        V3p0Ky93ZlJXUFQ0T1hXRWVrbi84Z0EKLS0tIHhFVlVtdlJRcXVjS2FCWHM5UVFK
        MXp6RE1KUi83Mm91amUvTGVZb3doTjgKRjuuzuzyp4Aap3kfS0+fMYZpPprEU0ON
        er6dCbpKtwB1+m5A8rIIT48XGM61DAN9ruEbCityPhyVWg2ITZqUgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-09T07:53:48Z"
  mac: ENC[AES256_GCM,data:iCfdli4tN/NUUMHFeQX0qof4SS7bUjfScsxFDa6u8vDhmmq1jqJi3tdBf4omY0G+HhKHN+Kv6Fbx6BplcMp8I+inJs9URZ7spdmkrQrdYeHEoUC009r+psajaWL1cdpDS5Bznz/joByZcE9ywfFhLy14fTtelRR+j+nIWL1KtLU=,iv:PgqTpEubZc4mgms1Wzn7Ko4NBrodyF4gzDVuFaVCBOk=,tag:cNn469o6jzT0Ur7GLByHnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
