---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.200.15.254:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.200.15.254"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "ms1"
    ipAddress: "10.200.15.51"
    installDiskSelector:
      serial: "1925E20E2038"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/743d942690991fb5b20d07e54b6d33c60b19d7918e14d61173d79e718ebc0b47
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:77:cf:36"
        dhcp: false
        addresses:
          - "10.200.15.51/24"
        routes:
          - gateway: "10.200.15.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.200.15.254"
  - hostname: "ms2"
    ipAddress: "10.200.15.52"
    installDiskSelector:
      serial: "220628801124"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/743d942690991fb5b20d07e54b6d33c60b19d7918e14d61173d79e718ebc0b47
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:78:f1:32"
        dhcp: false
        addresses:
          - "10.200.15.52/24"
        routes:
          - gateway: "10.200.15.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.200.15.254"
  - hostname: "ms3"
    ipAddress: "10.200.15.53"
    installDiskSelector:
      serial: "22061X806789"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/743d942690991fb5b20d07e54b6d33c60b19d7918e14d61173d79e718ebc0b47
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:78:f8:4a"
        dhcp: false
        addresses:
          - "10.200.15.53/24"
        routes:
          - gateway: "10.200.15.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.200.15.254"
  - hostname: "blade5"
    ipAddress: "10.200.15.35"
    installDisk: "/dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800811"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de1619e16531ddff67ccb4ce636a5e3ba5197eb4fc0e8421f095ec50ce9d26a6
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e4:5f:01:ec:16:b4"
        dhcp: false
        addresses:
          - "10.200.15.35/24"
        routes:
          - gateway: "10.200.15.1"
            network: 0.0.0.0/0
        mtu: 1500
  - hostname: "blade6"
    ipAddress: "10.200.15.36"
    installDisk: "/dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800731"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de1619e16531ddff67ccb4ce636a5e3ba5197eb4fc0e8421f095ec50ce9d26a6
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e4:5f:01:ec:16:a5"
        dhcp: false
        addresses:
          - "10.200.15.36/24"
        routes:
          - gateway: "10.200.15.1"
            network: 0.0.0.0/0
        mtu: 1500
  - hostname: "blade7"
    ipAddress: "10.200.15.37"
    installDisk: "/dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800801"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de1619e16531ddff67ccb4ce636a5e3ba5197eb4fc0e8421f095ec50ce9d26a6
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e4:5f:01:ec:16:9c"
        dhcp: false
        addresses:
          - "10.200.15.37/24"
        routes:
          - gateway: "10.200.15.1"
            network: 0.0.0.0/0
        mtu: 1500
  - hostname: "blade8"
    ipAddress: "10.200.15.38"
    installDisk: "/dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800737"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de1619e16531ddff67ccb4ce636a5e3ba5197eb4fc0e8421f095ec50ce9d26a6
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e4:5f:01:ec:16:5a"
        dhcp: false
        addresses:
          - "10.200.15.38/24"
        routes:
          - gateway: "10.200.15.1"
            network: 0.0.0.0/0
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

