---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync
components:
  - ../../components/common
resources:
  # Flux-Kustomizations
  - ./kopia/ks.yaml
  - ./volsync/ks.yaml
