---
# yaml-language-server: $schema=https://schemas.bykaj.io/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: plugin-barman-cloud-crds
spec:
  interval: 1h
  url: https://github.com/cloudnative-pg/plugin-barman-cloud.git
  ref:
    tag: v0.11.0
  ignore: |
    # exclude
    /*
    # include
    !config/crd/bases/barmancloud.cnpg.io_objectstores.yaml
---
# yaml-language-server: $schema=https://schemas.bykaj.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name plugin-barman-cloud-crds
  namespace: &namespace database
spec:
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: objectstores.barmancloud.cnpg.io
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: *name
  targetNamespace: *namespace
