---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HOMEPAGE_VAR_LATITUDE: "{{ .HASS_LATITUDE }}"
        HOMEPAGE_VAR_BAZARR_TOKEN: "{{ .BAZARR_API_TOKEN }}"
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARED_K8S_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_HOMEPAGE_TOKEN }}"
        ## Downloads
#        HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .LIDARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_QBITTORRENT_USER: "{{ .QBITTORRENT_USER }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_UHD_API_KEY: "{{ .RADARR_UHD_API_KEY }}"
#        HOMEPAGE_VAR_SABNZBD_API_KEY: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
#        HOMEPAGE_VAR_JELLYFIN_API_KEY: "{{ .JELLYFIN_HOMEPAGE_API_KEY }}"
#        HOMEPAGE_VAR_AUTOBRR_API_KEY: "{{ .AUTOBRR_API_KEY }}"
        HOMEPAGE_VAR_OVERSEERR_TOKEN: "{{ .OVERSEERR_API_KEY }}"
        HOMEPAGE_VAR_PLEX_API_KEY: "{{ .PLEX_TALOS_API_TOKEN }}" # Uses the devices api token from https://plex.tv/api/v2/server/access_tokens?auth_token=
        HOMEPAGE_VAR_TAUTULLI_TOKEN: "{{ .TAUTULLI_API_KEY }}"
        HOMEPAGE_VAR_DSM_USER: "{{ .DSM918_HOMEPAGE_USER }}"
        HOMEPAGE_VAR_DSM_PASSWORD: "{{ .DSM918_HOMEPAGE_PASSWORD }}"
#        HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
#        HOMEPAGE_VAR_PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        HOMEPAGE_VAR_UNIFI_USER: "{{ .HOMEPAGE_VAR_UNIFI_USER }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .HOMEPAGE_VAR_UNIFI_PASSWORD }}"
        HOMEPAGE_VAR_UNIFI_HOST: "{{ .HOMEPAGE_VAR_UNIFI_HOST }}"
        HOMEPAGE_AUTHENTIK_HOMEPAGE_TOKEN: "{{ .AUTHENTIK_HOMEPAGE_TOKEN }}"
        HOMEPAGE_VAR_PIHOLE_API_TOKEN: "{{ .PIHOLE_API_TOKEN }}"
        HOMEPAGE_VAR_HASS_API_TOKEN: "{{ .HASS_LONG_LIVED_TOKEN }}"
        HOMEPAGE_VAR_GRAFANA_USER: "{{ .GRAFANA_ADMIN_USER }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        HOMEPAGE_VAR_TDARR_TOKEN: "{{ .TDARR_TOKEN }}"
  dataFrom:
    - extract:
        key: authentik
#    - extract:
#        key: autobrr
    - extract:
        key: bazarr
    - extract:
        key: cloudflare
    - extract:
        key: cloudflare-tunnel-id
#    - extract:
#        key: cluster
    - extract:
        key: home-assistant
    - extract:
        key: homepage
#    - extract:
#        key: immich
#    - extract:
#        key: jellyfin
    - extract:
        key: lidarr
    - extract:
        key: dsm918
    - extract:
        key: grafana
    - extract:
        key: overseerr
#    - extract:
#        key: paperless
    - extract:
        key: qbittorrent
    - extract:
        key: pihole-exporter-secret
    - extract:
        key: plex
    - extract:
        key: prowlarr
#    - extract:
#        key: qbittorrent
    - extract:
        key: radarr
    - extract:
        key: radarr-uhd
#    - extract:
#        key: sabnzbd
    - extract:
        key: sonarr
    - extract:
        key: tautulli
    - extract:
        key: tdarr
    - extract:
        key: unifi
