---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nut-exporter
  namespace: &namespace monitoring
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
  path: ./kubernetes/apps/monitoring/nut-exporter/app
#  postBuild:
#    substituteFrom:
#      - name: cluster-secrets
#        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 1h
