---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_MEDIA_SERVER}"
    path: /volume2/piNFS01/flux-cluster/nextcloud
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nextcloud-nfs
  resources:
    requests:
      storage: 1Mi
