---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app democratic-csi-iscsi-synology
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.iscsi-synology"
    driver:
      existingConfigSecret: democratic-csi-secret
      image: ghcr.io/democratic-csi/democratic-csi:v1.9.5
      config:
        driver: synology-iscsi
    # https://kubernetes-csi.github.io/docs/external-provisioner.html
    externalProvisioner:
      image: registry.k8s.io/sig-storage/csi-provisioner:v6.1.0
    # https://kubernetes-csi.github.io/docs/external-resizer.html
    externalResizer:
      image: registry.k8s.io/sig-storage/csi-resizer:v2.0.0
    # https://kubernetes-csi.github.io/docs/external-snapshotter.html
    externalSnapshotter:
      image: registry.k8s.io/sig-storage/csi-snapshotter:v8.4.0
    # https://github.com/kubernetes-csi/external-health-monitor
    externalHealthMonitorController:
      enabled: true
      image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.16.0
    csiProxy:
      image: ghcr.io/democratic-csi/csi-grpc-proxy:v0.5.7
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
    node:
      cleanup:
        image: docker.io/busybox:1.37.0
      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.9.5
        resources:
          requests:
            cpu: 15m
            memory: 150Mi
      driverRegistrar:
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.16.0
      format:
        ext4:
        customOptions:
          - -E
          - nodiscard
    storageClasses:
      - name: synology-iscsi-retain
        defaultClass: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
        mountOptions: []
      - name: synology-iscsi-delete
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
        mountOptions: []
    volumeSnapshotClasses:
      - name: synology-iscsi
        parameters:
          lunSnapshotTemplate: |
            is_locked: true

            # https://kb.synology.com/en-me/DSM/tutorial/What_is_file_system_consistent_snapshot
            # Note that app consistent snapshots require a working Synology Storage Console. Otherwise both values will have
            # equivalent behavior.
            is_app_consistent: true
        secrets:
          snapshotter-secret:
